spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: user
      password: password
      authentication-database: admin
      database: yourdatabase

  #      url: mongodb://ocalhost:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false
  datasource:
    hikari:
      username: root
      password: leeves777
      jdbc-url: jdbc:mysql://localhost:3306/springdemo
      driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: DEBUG
  redis:
    host: localhost
    port: 6379
    password: leeves777
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:./test
#    username: sa
#    password: 123123
logging:
  level:
    com.myself.springdemo.mapper.UserMapper: DEBUG

rabbitmq:
  template:
    exchange: spring-boot-exchange
    routing-key: foo
    receive-timeout: 3000
    default-receive-queue: spring-boot
  stream:
    username: guest
    password: guest

redis:
  uuidprefix: 9999

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
#  sql:
#    init:
#      schema-locations: classpath:static/schema-h2.sql
#server:
port: 8088
#      data-locations: classpath:static/data-h2.sql


